---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Spatial pharmacokinetic and pharmacodynamic modeling in airway mucus

These scripts were used to study the spatial distribution of drugs in airway mucus and the spatial antimicrobial pharmacodynamics using spatial modeling.

### Scripts

The folder scripts contains the following files:
  
-   **01 tutorial fig.R**, uses small molecules as an example to showcase the spatial pharmacokinetics in the airway mucus (Fig.2)
-   **02 impact factor.R**, identifies the influential factors of the spatial PK from molecule/particle size (radius, r), mucin binding affinity, and half-lives, and under systems with different mucin concentration and muco-ciliary clearance (Fig.3; Fig.S2)
-   **03 spatialPD.R**, investigates the impact of drug distribution on drug efficacy using imipenem as a case study (Fig.6; Fig.S1,4,6).
-   **04 thin source.R**, compares the spatial pharmacokinetics with thin source and infinite source (Fig.S7).
-   **05 delayed distribution.R**, generates the boundary condition with different extents of delay (Fig.S8).

### Functions

Above scripts depend on certain functions written in separate files.

-   **get_D_coeff.R**, contains the functions for calculating the mucin-dependent viscosity and diffusion coefficient.
-   **pde.R**, contains the discretized partial differential equations (PDEs) for describing the spatial pharmacokinetics in airway mucus.
-   **pde_pkpd_emax.R**, contains the PDEs for describing the spatial pharmacokinetics and pharmacodynamics in airway mucus.
-   **pde_boundary.R**, contains the PDEs for describing the spatial pharmacokinetics under different boundary conditions (thin or infinite source).

