######################################################################
### The script is used to investigate the impact of spatial distribution ----
# of drug on the pharmacodynamics with imipenem as an example ----
# y.guo@lacdr.leidenuniv.nl - July 2025
######################################################################
rm(list = ls(all = TRUE))

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 0 - Load libraries   ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(reshape2)
library(rxode2)

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 1 - Source files   ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# function
source("functions/get_D_coeff.R") ## get the diffusion coefficient
source("functions/pde_pkpd_emax.R") ## PDE function (elimination)

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 2 - Plasma PK of Imipenem   ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## dosing schedules of interest
ii <- rep(6,6) # unit: hour
dur <- c(0.5, 0.5, 0.5, 6, 6, 6) # unit: hour
type_name <- rep(c("intermittent infusion", "continuous infusion"), each = 3)
amt <- rep(c(250,500,1000),2)

dose_name <- rep(c("dose = 250mg",
                   "dose = 500mg",
                   "dose = 1000mg"),2)

dosing <- as.data.frame(cbind(ii, dur, type_name, amt, dose_name))
dosing

for(j in c(1,2,4)){
  dosing[,j] <- as.numeric(dosing[,j])
}
dosing

## simulate plasma PK profile
mod_H <- RxODE({
  
  CL ~  0.192; # L/min, reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4876184/
  V1 ~ 9.37; # L 
  V2 ~ 6.41; # L 
  Q ~ 0.228; # L/min 
  
  d/dt(C1)   = -(CL/V1)*C1-(Q/V1)*C1+(Q/V2)*C2;
  d/dt(C2)    = (Q/V1)*C1-(Q/V2)*C2 ;
  
  Con1 = C1/V1;
  Con2 = C2/V2;
})

# create a blank list
dat.pk.plasma_clct <- list()

# test
i = 1

# run in loop
for (i in 1:6) {
  
    # assign parameter
    amt_ok <- dosing[i, "amt"] # mg
    dur_ok <- dosing[i, "dur"] # hour
    ii_ok <- dosing[i, "ii"] # hour
    
    ## Create event table
    event.pk <- et() %>%
      # dosing events
      et(id = 1,
         amt = amt_ok,
         cmt = 1,
         dur = dur_ok*60,
         ii = ii_ok*60,  
         addl = 72/ii_ok - 1) %>% 
      # sampling events
      et(seq(from = 0, to = 72*60, by = 1)) %>% 
      as_tibble()
    
    ## Simulate plasma PK
    set.seed(2021)
    dat.pk.plasma <- rxSolve(mod_H, event = event.pk, addDosing = F) %>% 
      distinct() %>%
      mutate(description = dosing[i, "type_name"])  %>% 
      mutate(feature = dosing[i, "dose_name"])
    
    dat.pk.plasma_clct[[i]] <- dat.pk.plasma

    i = i + 1
  
}

# visualize plasma PK profiles
all_plasma <- do.call(rbind, dat.pk.plasma_clct)
all_plasma$description <- factor(all_plasma$description, levels = unique(all_plasma$description))
all_plasma$feature <- factor(all_plasma$feature, levels = unique(all_plasma$feature))
all_plasma_plot <- ggplot(data = all_plasma, aes(x = time/60, y = Con1)) +
  geom_line() +
  scale_x_continuous(name = "Time (hour)", breaks = c(0:100)*4) +
  scale_y_continuous(name = "Concentration (mg/L)") +
  facet_grid(description ~ feature) +
  theme_bw()
all_plasma_plot

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 3 - Generate baseline spatial CFU data  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## data structure
y_axis <- seq(from = 0, to = 500, by = 25) # steps
step <- 500/25 + 1  # steps in depths
x_axis <- rep(0, step)
patterns <- c("Homogenous\ndistribution",
              "Decreasing\ngradient",
              "Increasing\ngradient")
label <- rep(patterns,
             each = step)  # distribution pattern of bacteria in mucus

## generate CFU data
a <- 5.58  # exponent index for the baseline bacteria count, log10 cfu/mL
set.seed(2022)
CFU1 <- rep(10^a,step)  # homogeneous distribution

lognum <- rpois(step, a) # random number generated by Poisson distribution
num <- 10^lognum 
CFU2 <- sort(num ,decreasing=TRUE) # decrease : log gradient; decreased distribution with depth
CFU3 <- sort(num,decreasing=FALSE) # increase : log gradient; increased distribution with depth
CFU <- c(CFU1, CFU2, CFU3)
cfu_baseline <- list(CFU1, CFU2, CFU3)

CFU_baseline <- as.data.frame(cbind("x_axis" = rep(x_axis, 3),
                                    "y_axis" = rep(y_axis, 3),
                                    "pattern" = label,
                                    "CFU" = CFU)) 
CFU_baseline$CFU <- as.numeric(CFU_baseline$CFU)
CFU_baseline <- CFU_baseline %>% 
  mutate(logCFU = log10(CFU))

## visualize baseline bacterial CFU count
CFU_baseline$pattern <- factor(CFU_baseline$pattern, 
                             levels = c("Homogenous\ndistribution", "Increasing\ngradient", "Decreasing\ngradient"))
CFU_baseline$y_axis <- factor(CFU_baseline$y_axis, 
                               levels = unique(CFU_baseline$y_axis))
cfu_plot <- ggplot(CFU_baseline, aes(x_axis, y_axis, fill = logCFU)) +
  geom_tile() +
  guides(fill = guide_colorbar(
    title.position = "top",
    direction = "vertical")) +
  scale_fill_distiller(palette = 7,
                       direction = 1) +
  scale_x_discrete(name = "Baseline of Pathogen") + 
  scale_y_discrete(name = "Distance (μm)", breaks = c(0:50)*10) +
  labs(fill = "Bacteria count\n (log10 CFU/mL)") +
  theme_bw() +
  theme(text = element_text(family = "sans", color = "black", size = 12),
        axis.text.y = element_text(family = "sans", color = "black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.key.width = unit(0.01, "npc"),
        strip.text = element_text(color = "black", size = 10, face = "plain"),
        axis.title.y = element_text(margin=margin(r=10)))+
  facet_grid(cols = vars(pattern)) 
cfu_plot # PDF 5 8cm
ggsave(cfu_plot, file = "figure/cfu_plot.pdf", width = 18, height = 10, units = "cm", device = cairo_pdf)
ggsave(cfu_plot, file = "figure/cfu_plot.tiff", width = 18, height = 10, units = "cm", dpi = 600)
# calculate the initial CV
CFU2_log <- CFU_baseline$logCFU[CFU_baseline$pattern == "Increasing\ngradient"]
CFU2_log
100*sd(CFU2_log)/mean(CFU2_log) # 46.45
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 4 - Generate spatial PK/PD data  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# case example: PKPD model - planktonic phenotype - imipenem
listdata <- list()
listdata_CV <- list()
dosing$sum_bact <- NA
dosing$sum_concf <- NA
dosing

list_dosing <- list(dosing %>% mutate(pattern = patterns[1]),
                    dosing %>% mutate(pattern = patterns[2]),
                    dosing %>% mutate(pattern = patterns[3]))

for (m in 1:3) {
  
  for (i in 1:6){
  
    start_time <- Sys.time()
    
    # assign parameter
    dat.pk.plasma <- dat.pk.plasma_clct[[i]]
    condition <- cfu_baseline[[m]]
    
    dat.pk.mucus <- pde(db.pk = 0.444*dat.pk.plasma$Con1, # plasma PK
                        coef.diff = Diffusion_coeff(1, vis(2e-5)) , # diffusion coefficient um^2/sec
                        kon = 100 , # binding rate /(M*sec)   
                        koff = 0.1, # unbinding rate /sec
                        Tmucin = 2e-5,# concentration of total mucin mol/L
                        dt = 0.5, # step size time in seconds
                        span.t = 72, # observation time span in hours #previously observe to = 72*60, no chang it to 24hour
                        dx = 25, # step size depth in um
                        span.x = 500, # observation depth span in um
                        clr = 0,# elimination rate in 1/s
                        pd.bl =condition, # baseline structure of pathogen
                        kgs = 1.67e-4, # natural growth rate of Sensitive population of bacteria (s-1)
                        kgr = 0, # natural growth rate of Resistant population of bacteria (s-1)
                        ksr = 9.86e-6 , # transfer rate (s-1)
                        slopeS = 2.38e-4, # killing rate for resistant species
                        slopeR = 3.78e-5, # killing rate for resistant species
                        Bmax = 10^9.52) # maximum bacteria count (CFU/mL)             
    
    dat.pk.mucus.ok <- dat.pk.mucus %>% 
      rename(Conc_F = CONC_FREE) %>% 
      rename(Conc_B = CONC_BIND) %>%
      left_join(dat.pk.plasma, by = c("TIME" = "time")) %>% 
      mutate(Ratio = Conc_F/Con1,
             LogS = log10(Sensitive),
             LogR = log10(Resistant),
             LogBact = log10(Sensitive + Resistant),
             Bact = Sensitive + Resistant,
             Pattern = patterns[m],
             feature = unique(dat.pk.plasma$feature),
             description = unique(dat.pk.plasma$description))  
    
    dat.pk.mucus.ok$LogBact[dat.pk.mucus.ok$LogBact < 0] <- 0
    dat.pk.mucus.ok$LogR[dat.pk.mucus.ok$LogR < 0] <- 0
    dat.pk.mucus.ok$LogS[dat.pk.mucus.ok$LogS < 0] <- 0
    
    k = (m - 1)*6 + i
    listdata[[k]] <- dat.pk.mucus.ok
    
    
    # to calculate the cv
    input_data <- dat.pk.mucus.ok[-1,] %>%
      group_by(TIME) %>%
      summarise(
        CV_F = ifelse(mean(Conc_F, na.rm = TRUE) == 0, NA_real_, 
                      100 * sd(Conc_F, na.rm = TRUE) / mean(Conc_F, na.rm = TRUE)),
        CV_B = ifelse(mean(Conc_B, na.rm = TRUE) == 0, NA_real_, 
                      100 * sd(Conc_B, na.rm = TRUE) / mean(Conc_B, na.rm = TRUE)),
        CV_S = ifelse(mean(Sensitive, na.rm = TRUE) == 0, NA_real_, 
                      100 * sd(Sensitive, na.rm = TRUE) / mean(Sensitive, na.rm = TRUE)),
        CV_R = ifelse(mean(Resistant, na.rm = TRUE) == 0, NA_real_, 
                      100 * sd(Resistant, na.rm = TRUE) / mean(Resistant, na.rm = TRUE)),
        CV_T = ifelse(mean(Bact, na.rm = TRUE) == 0, NA_real_, 
                      100 * sd(Bact, na.rm = TRUE) / mean(Bact, na.rm = TRUE))
      ) %>% 
      mutate(Pattern = patterns[m],
             feature = unique(dat.pk.plasma$feature),
             description = unique(dat.pk.plasma$description))  
    
    listdata_CV[[k]] <- input_data
    
    list_dosing[[m]][i, c("sum_bact","sum_concf")] <-
      c(sum(dat.pk.mucus.ok$Bact),
        sum(dat.pk.mucus.ok$Conc_F))
    
    
    end_time <- Sys.time()
    
    cat("time of simulation round: ", end_time - start_time, k, "\n")
    
    i = i + 1
    
    }
    m = m+1
}

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 5 - plot for the spatial distribution ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
all_data <- do.call(rbind, listdata)
## organize the order of different values for each factor
all_data$description <- factor(all_data$description, levels = unique(all_data$description))
all_data$feature <- factor(all_data$feature, levels = unique(all_data$feature))
all_data$Pattern <- factor(all_data$Pattern, levels = unique(all_data$Pattern))

## plot spatial PK
pCon_f <- ggplot(all_data, aes(TIME/60, DEPTH, fill = Conc_F)) +
  geom_tile() +
  guides(fill = guide_colorbar(
    title.position = "top",
    direction = "vertical")) +
  scale_fill_distiller(palette = 4,
                       direction = 1) +
  scale_x_continuous(name = "Time (hour)", breaks = c(0:100)*10) + 
  scale_y_continuous(name = "Distance (μm)") +
  theme_bw() +
  theme(text = element_text(family = "sans", color = "black", size = 9),
        axis.text = element_text(family = "sans", color = "black"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7.5),
        legend.key.width = unit(0.005, "npc"),
        legend.key.height = unit(0.3, 'cm'),
        strip.text = element_text(color = "black", size = 7.5, face = "plain"))+
  facet_grid(feature ~ description + Pattern)
pCon_f

## plot spatial PD
pcfu_plots <- list()
for(j in 1 : 3){
  
  # combine the data for each factor
  set_data <- rbind(listdata[[(j-1)*6 + 1]],
                    listdata[[(j-1)*6 + 2]],
                    listdata[[(j-1)*6 + 3]],
                    listdata[[(j-1)*6 + 4]],
                    listdata[[(j-1)*6 + 5]],
                    listdata[[(j-1)*6 + 6]])

  # organize the order of different values for each factor
  set_data$description <- factor(set_data$description, levels = unique(set_data$description))
  set_data$feature <- factor(set_data$feature, levels = unique(set_data$feature))
  
  pcfu_plot <- ggplot(set_data, aes(TIME/60, DEPTH, fill = LogBact)) +
    geom_tile() +
    guides(fill = guide_colorbar(
      title.position = "top",
      direction = "vertical")) +
    scale_fill_distiller(palette = 7,
                         direction = 1) +
    scale_x_continuous(limits=c(0, 72),name = "Time (hour)", breaks = c(0:100)*10) + 
    scale_y_continuous(name = "Distance (μm)") +
    theme_bw() +
    theme(text = element_text(family = "sans", color = "black", size = 12),
          axis.text = element_text(family = "sans", color = "black"),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 10),
          legend.key.width = unit(0.01, "npc"),
          strip.text = element_text(color = "black", size = 9.5, face = "plain"))+
    labs(fill = "Bacteria count\n (log10 CFU/mL)") +
    facet_grid(description ~ feature)
  pcfu_plot # 8 10 cm
  
  pcfu_plots[[j]] <- pcfu_plot
  
  j <-  j + 1
}

figure5 <- ggarrange(pcfu_plots[[1]], pcfu_plots[[3]],
                     labels = c("B","C"),
                     nrow = 2, ncol = 1,
                     font.label = list(size = 18))
figure5 


# save the data
save(file = "result/f5_spatialPD.Rdata", listdata)
save(file = "result/f5_spatialPD_cv.Rdata", listdata_CV)
save(file = "result/f5_spatialPD_dosing.Rdata", list_dosing)


##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ 6 - Time to complete clearance ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
all_spatial <- do.call(rbind,listdata)
# calculation
tte_data <- list()

alldata_sp <-all_spatial %>% 
  mutate(type = paste0(description,"-",feature,"-",Pattern))

alldata_sp_sum <- alldata_sp %>%
  group_by(TIME, type) %>%
  summarise(SUMLogBact = sum(LogBact))


alldata_sp_sum %>% 
  ggplot() +
  geom_line(aes(TIME/60, SUMLogBact)) +
  scale_x_continuous(name = "Time (hour)", breaks = c(0:100)*4) +
  scale_y_continuous(name = "Sum_concf") +
  facet_grid(type~.) +
  theme(text = element_text(family = "sans", color = "black", size = 8),
        axis.text = element_text(family = "sans", color = "black"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.key.width = unit(0.01, "npc"),
        strip.text = element_text(color = "black", size = 6, face = "plain"))+
  theme_bw()

# conclusion: the bacteria only got elliminited under 1100 mg dosage

# continuous infusion-dose = 1100mg-Decreasing\ngradient
alldata_sp_sum_conti <- alldata_sp_sum %>% 
  filter(type == "continuous infusion-dose = 1100mg-Increasing\ngradient")

alldata_sp_sum <- alldata_sp_sum %>% 
  filter(TIME != 0)


tte_data_all <- list()
for (j in 1:length(unique(alldata_sp_sum$type)) ) {
  tte_data <- data_frame()
  input_cv <- alldata_sp_sum[alldata_sp_sum$type == unique(alldata_sp_sum$type)[j],]
  
  d = unique(input_cv$type)
  
  for(i in 1 : 4320 ) { # 4320 rows (minutes, = 72 hours) for each subset data

    b = input_cv$SUMLogBact[i] # the summary of concentrations at all different distances from the blood-mucus interface
    
    if (b == 0) {
      tte_data_i <- data_frame(Time=i/60, time = i, type = d)
      
      tte_data <- rbind(tte_data,tte_data_i) 
    }
    
    i = i + 1
  }
  
  tte_data_all[[j]] <- tte_data
  
  j = j + 1
  
}

save(file = "result/f5_tte.Rdata", tte_data_all)
